create table energieverbrauch
(
    Kennummer     int         not null
        primary key,
    GruppenNr     int         not null,
    Nahrungsarten varchar(60) not null,
    Verbrauch     float       not null
)
    collate = latin1_general_ci;

create index gruppe
    on energieverbrauch (GruppenNr);

create index nahrungsarten
    on energieverbrauch (Nahrungsarten);

INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (1, 1, 'Hartweizen II (in Mehl ber.)', 11.95);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (2, 1, 'Weichweizen (in Mehl ber.)', 51.71);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (3, 1, 'Dinkel (in Mehl berechnet)', 0.57);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (4, 1, 'Roggen (in Mehl berechnet)', 1.25);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (5, 1, 'Mischel (in Mehl berechnet)', 0.43);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (6, 1, 'Gerste II (in Mehl berechnet)', 0.72);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (7, 1, 'Hafer (in Mehl berechnet)', 1.01);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (8, 1, 'Mais (in Mehl berechnet)', 1.51);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (9, 1, 'Reis, geschält', 4.83);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (10, 2, 'Kartoffeln,  -produkte', 47.07);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (11, 2, 'Stärke', 0.22);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (12, 3, 'Zucker', 43.13);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (13, 3, 'Sirup', 1.37);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (14, 3, 'Honig', 1.41);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (15, 4, 'Hülsenfrüchte', 1.15);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (16, 4, 'Erdnüsse', 0.87);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (17, 4, 'Mandeln', 1.12);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (18, 4, 'Kastanien', 0.45);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (19, 4, 'Baumnüsse, Haselnüsse', 2.36);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (20, 4, 'Kakao', 5.45);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (21, 5, 'Weiss- u. Rotkabis', 3.62);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (22, 5, 'Blumenkohl', 2.65);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (23, 5, 'Rosenkohl', 0.43);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (24, 5, 'Wirz', 1.02);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (25, 5, 'Kohlrabi', 0.65);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (26, 5, 'Broccoli', 0.92);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (27, 5, 'andere Kohlgewächse', 1.13);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (28, 5, 'Randen', 1.72);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (29, 5, 'Karotten', 8.73);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (30, 5, 'Weisse Rüben', 0.73);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (31, 5, 'Sellerie', 1.34);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (32, 5, 'Fenchel', 1.59);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (33, 5, 'Schwarzwurzeln', 0.04);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (34, 5, 'Radieschen', 0.24);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (35, 5, 'Rettiche', 0.42);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (36, 5, 'andere Wurzel u.Knol', 1.74);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (37, 5, 'Artischocken', 0.21);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (38, 5, 'Rhabarber', 0.32);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (39, 5, 'Mangold', 0.39);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (40, 5, 'Spargeln', 1.2);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (41, 5, 'Treibzichorien', 1.99);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (42, 5, 'Kopfsalat, Lattich', 3.77);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (43, 5, 'Endivien', 2.55);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (44, 5, 'Nüsslisalat', 0.55);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (45, 5, 'Zuckerhut', 0.6);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (46, 5, 'Spinat', 2.75);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (47, 5, 'andere Salate', 5.48);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (48, 5, 'Bohnen', 2.18);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (49, 5, 'Erbsen', 1.03);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (50, 5, 'Tomaten', 9.08);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (51, 5, 'Auberginen', 0.53);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (52, 5, 'Zwiebeln, Knoblauch', 4.79);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (53, 5, 'Lauch', 1.83);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (54, 5, 'Gurken', 3.95);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (55, 5, 'Peperoni grün/rot', 2.16);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (56, 5, 'Zucchetti', 1.71);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (57, 5, 'Schnittlauch Petersilie', 0.46);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (58, 5, 'andere Gemüse', 0.16);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (59, 5, 'Pilze', 1.38);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (60, 5, 'Konserven (in Frischgewicht)', 14.15);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (61, 6, 'Äpfel', 18.45);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (62, 6, 'Birnen', 4.22);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (63, 6, 'Kirschen', 1.61);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (64, 6, 'Zwetschgen und Pflaumen', 0.97);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (65, 6, 'Aprikosen', 2.52);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (66, 6, 'Pfirsiche', 4.43);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (67, 6, 'Erdbeeren', 3.53);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (68, 6, 'Beeren', 3.2);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (69, 6, 'Melonen', 4.64);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (70, 6, 'Trauben', 5.5);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (71, 6, 'Bananen', 9.51);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (72, 6, 'Orangen, Mandarinen', 14.74);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (73, 6, 'Zitronen', 2.61);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (74, 6, 'Grapefruits', 1.47);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (75, 6, 'Anderes frisches Obst', 3.04);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (76, 6, 'Andere Obstkonserven', 4.27);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (77, 7, 'Rind, Filet, Entrecote', 1.36);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (78, 7, 'Rind, Braten', 0.59);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (79, 7, 'Rind, Gehacktes', 2.54);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (80, 7, 'Rind, Siedfleisch', 0.76);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (81, 7, 'Rind, Voressen', 0.67);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (82, 7, 'Rind, übriges', 1.44);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (83, 7, 'Kalb, Plätzli', 0.64);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (84, 7, 'Kalb, Braten', 0.25);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (85, 7, 'Kalb, Voressen', 0.38);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (86, 7, 'Kalb, übriges', 1);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (87, 7, 'Schwein, Filet', 0.35);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (88, 7, 'Schwein, Koteletten', 2.02);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (89, 7, 'Schwein, Plätzli', 1.72);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (90, 7, 'Schwein, Braten', 1.74);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (91, 7, 'Schwein, Geräuchertes', 2.18);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (92, 7, 'Schwein, Geschnetzeltes', 0.56);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (93, 7, 'Schwein, Voressen', 0.91);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (94, 7, 'Schwein, übriges', 1.48);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (95, 7, 'Schinken', 2.54);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (96, 7, 'Salami', 0.6);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (97, 7, 'Aufschnitt', 0.94);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (98, 7, 'Fleischkäse', 1.31);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (99, 7, 'Trockenfleisch', 0.77);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (100, 7, 'übrige Charcuterie', 1.5);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (101, 7, 'Bratwürste', 2.58);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (102, 7, 'Cervelas', 2.96);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (103, 7, 'Wienerli', 2.32);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (104, 7, 'übrige Wurst', 5.03);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (105, 7, 'Schaffleisch', 1.26);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (106, 7, 'Ziegenfleisch', 0.09);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (107, 7, 'Pferdefleisch', 0.63);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (108, 7, 'Geflügel', 10.25);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (109, 7, 'Kaninchen', 0.66);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (110, 7, 'Wild', 0.75);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (111, 7, 'Organteile', 2.61);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (112, 8, 'Eier und Eikonserven', 10.62);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (113, 9, 'Frisch', 3.97);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (114, 9, 'Konserven', 3.77);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (115, 10, 'Vollmilch', 69.7);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (116, 10, 'Standardisierte Milch', 24.05);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (117, 10, 'Magermilch', 3);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (118, 10, 'Joghurt', 16.9);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (119, 10, 'Quark', 1.85);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (120, 10, 'Kondensmilch', 0.29);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (121, 10, 'Vollmilchpulver', 0.4);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (122, 10, 'Magermilchpulver', 2.84);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (123, 10, 'Emmentaler', 1.13);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (124, 10, 'Greyerzer', 1.98);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (125, 10, 'Sbrinz', 0.32);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (126, 10, 'Tilsiter', 0.77);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (127, 10, 'Appenzeller', 0.43);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (128, 10, 'Weichkäse', 3.71);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (129, 10, 'andere Hart- u. HalbhartKäse', 4.9);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (130, 10, 'Magerkäse', 0.15);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (131, 10, 'Schmelzkäse', 1.7);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (132, 10, 'Vollrahm', 3.3);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (133, 10, 'Halbrahm', 1.7);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (134, 10, 'Kaffeerahm', 4.6);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (135, 10, 'Fertigfondue', 0.5);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (136, 11, 'Olivenöl', 0.42);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (137, 11, 'Übrige pfl. Öle, Fette', 13.25);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (138, 11, 'Butter', 5.25);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (139, 11, 'Kalorienverminderte Butter', 0.03);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (140, 11, 'Eingesottene Butter', 0.94);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (141, 11, 'Schweineschmalz', 0.91);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (142, 11, 'Rinderfett', 1.49);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (143, 12, 'Wein', 53.3);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (144, 12, 'Obstwein', 3.9);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (145, 12, 'Bier', 77.2);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (146, 12, 'Branntwein', 4.6);
INSERT INTO LB1.energieverbrauch (Kennummer, GruppenNr, Nahrungsarten, Verbrauch) VALUES (147, 13, 'Fruchtsäfte', 13.17);